version: "0.5"

processes:
  postgresql:
    command: 'pg_ctl start -o "-k ''$PGHOST''"'
    is_daemon: true
    shutdown:
      command: "pg_ctl stop -m fast"
    availability:
      restart: "always"
    readiness_probe:
      exec:
        command: "pg_isready"

  backend:
    command: cd backend && mvn clean install && mvn spring-boot:run
    depends_on:
      postgresql:
        condition: "process_started"

  webapp:
    command: cd webapp && npm run dev
    depends_on:
      backend:
        condition: "process_started"
    availability:
      restart: "always"
